parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            CategoryId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineCategoryId
            Color:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineColor
            ContactRequestId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineContactRequestId
            Content:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineContent
            Description:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineDescription
            Email:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineEmail
            ImageUrl:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineImageUrl
            Message:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineMessage
            Name:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineName
            Order:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineOrder
            Phone:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrinePhone
            PostId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrinePostId
            Title:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineTitle
            UrlSlug:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineUrlSlug

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Category:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/Category/Mapping'
                prefix: 'AlexAgile\Domain\Category'
                alias: Category
            ContactRequest:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/ContactRequest/Mapping'
                prefix: 'AlexAgile\Domain\ContactRequest'
                alias: ContactRequest
            Post:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/Post/Mapping'
                prefix: 'AlexAgile\Domain\Post'
                alias: Post
