parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            CategoryId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineCategoryId
                commented: true
            Color:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineColor
                commented: true
            Content:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineContent
                commented: true
            ImageUrl:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineImageUrl
                commented: true
            Order:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineOrder
                commented: true
            PostId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrinePostId
                commented: true
            Title:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineTitle
                commented: true
            UrlSlug:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineUrlSlug
                commented: true
            Email:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineEmail
                commented: true
            Password:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrinePassword
                commented: true
            UserId:
                class: AlexAgile\Infrastructure\Persistence\Doctrine\CustomType\DoctrineUserId
                commented: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Category:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/Category/Mapping'
                prefix: 'AlexAgile\Domain\Category'
                alias: Category
            Post:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/Post/Mapping'
                prefix: 'AlexAgile\Domain\Post'
                alias: Post
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AlexAgile/Infrastructure/Persistence/Doctrine/User/Mapping'
                prefix: 'AlexAgile\Domain\User'
                alias: User
