version: '3'

services:
  apache:
    build:
      dockerfile: ./docker/apache/Dockerfile
      context: .
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_SERVER_ADMIN=alexagile@alexagile.com
    networks:
      myapp-network:
        aliases:
          - apache
        ipv4_address: 172.28.0.10
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/public

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      myapp-network:
        aliases:
          - mysql
        ipv4_address: 172.28.0.20
    volumes:
      - myapp_mysql-data:/var/lib/mysql

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    expose:
      - 9000
    networks:
      myapp-network:
        aliases:
          - php
    volumes:
      - .:/var/www/public

networks:
  myapp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  myapp_mysql-data:
    driver: local
